apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cassandra-operator
    spec:
      containers:
      - name: cassandra-operator
        image: aslanbekirov/cassandra-operator:v0.0.1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name